---
- name: Ensure configuration
  sudo: true
  template:
    src: '{{ ntp_config_file_template }}'
    dest: '{{ ntp_config_file }}'
    owner: root
    group: root
    mode: '0644'
  notify: Restart NTP