---
- name: Install NTP
  yum: name={{ ntp_package_name }} state=installed

- name: Start NTP service and configure on boot startup
  service: name={{ ntp_service_name }} state={{ ntp_service_state }} enabled={{ ntp_service_enabled }}