---
- include_vars: '{{ item }}'
  with_first_found:
  - '{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml'
  - '{{ ansible_distribution }}.yml'
  - '{{ ansible_os_family }}.yml'
  tags:
  - ntp_install
  - ntp_config
  - ntp_service

- include: install.yml
  tags: ntp_install

- include: config.yml
  tags: ntp_config

- include: service.yml
  tags: ntp_service
